version: '1.0'

services:

  postgres:
    image: postgres:11.13
    container_name: t1_15_demo
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=t1_15_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000